version: '3.7'

services:
  mysql:
    image: mysql:$MYSQL_VERSION
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - LANG=C.UTF-8
      - TZ=Europe/UTC
    ports:
      - 23306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql/:rw
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
      - ./mysql/conf.d:/etc/mysql/conf.d/:ro


  nginx:
    image: nginx
    restart: always

    volumes:
      - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"

      # Let's Encrypt! (read-only)
      ## Certificates dir
      - "${LETSENCRYPT_ROOT:-/etc/letsencrypt}:/etc/letsencrypt:ro"
      ## ACME challenges dir
      - "${LETSENCRYPT_ACME:-/var/lib/letsencrypt}:/var/lib/letsencrypt:ro"

      # Static server
      - ./server/images:/etc/nginx/html/images:ro
      - ./server/agreements:/etc/nginx/html/agreements:ro

    ports:
      # Static
      - "80:80"
      - "443:443"

      # REST
      - "8443:8443"


    depends_on:
      - server

  server:
    image: ravioo/rabbit-backend:1.0
    environment:
      - CONTAINER_TIMEZONE=Europe/UTC
    volumes:
      #      - ./server/config:/home/backend/config:ro
      - ./server/logs:/home/backend/logs:rw
      - ./server/images:/home/backend/images:rw
      - ./server/config:/home/backend/config:ro
      - ./server/geoip:/home/backend/geoip:ro
    depends_on:
      - mysql


  # Let's Encrypt client for bootstrap
  certbot-bootstrap:
    image: certbot/certbot
    volumes:
      # Let's Encrypt! (read-write)
      ## Certificates dir
      - "${LETSENCRYPT_ROOT:-/etc/letsencrypt}:/etc/letsencrypt"
      ## ACME challenges dir
      - "${LETSENCRYPT_ACME:-/var/lib/letsencrypt}:/var/lib/letsencrypt"

    ports:
      - "80:80"

    entrypoint: [
      # common options
      "certbot",
      "--non-interactive", "--agree-tos",
      "--email",
      "${LETSENCRYPT_EMAIL:-pavelsarpov@gmail.com}",
      # bootstrap
      "certonly",
      "--standalone"
    ]

  # Let's Encrypt client for renew
  certbot:
    image: certbot/certbot
    volumes:
      # Let's Encrypt! (read-write)
      ## Certificates dir
      - "${LETSENCRYPT_ROOT:-/etc/letsencrypt}:/etc/letsencrypt"
      ## ACME challenges dir
      - "${LETSENCRYPT_ACME:-/var/lib/letsencrypt}:/var/lib/letsencrypt"

    entrypoint: [
      # common options
      "certbot",
      "--non-interactive", "--agree-tos",
      "--email",
      "${LETSENCRYPT_EMAIL:-pavelsarpov@gmail.com}",
    ]  # Let's Encrypt client for renew